### ISSUE TITLE
How to use this library? No Usage given.

### ISSUE THREAD

**Issue by bhishanpdl** [TC01/python-xkcd#13]
I was wondering how to use this library. 
It does not say anything about usage.

I downloaded the repo, and `python xkcd.py` gives nothing.

can we download xkcd jokes using this library?

**Comment by TC01** [comment]
I suppose it's true that the repository doesn't explicitly give instructions, and I could improve that somewhat by at least linking to PyPI.

However, respectfully, it sounds like you are not that familiar with Python-- or at least Python packaging-- given that your instinct was just to try running the "xkcd" module (which is not even marked as executable). So I would encourage you to read up on how Python libraries are [generally installed](https://packaging.python.org/tutorials/installing-packages/) and [built](https://setuptools.readthedocs.io/en/latest/setuptools.html). There is a "setup.py" file in the repository, and almost *all* Python packages use distutils/setuptools to build and install themselves; it is the most common mechanism for such things. 

Anyway. The package is [on PyPI](https://pypi.python.org/pypi/xkcd). You can install it via pip:

```
pip install xkcd
```

There is some linked API documentation [in the README](https://pythonhosted.org/xkcd/). Hopefully you can figure it out from there.
