### ISSUE TITLE
2x support

### ISSUE THREAD

**Issue by kristianbenoit** [TC01/python-xkcd#15]
There is an interface for high quality (2x) images. I think the python xkcd interface should provide support for this. See the html of a single page:
```html
...
<div id="comic">
    <img src="//imgs.xkcd.com/comics/a_b.png" ... srcset="//imgs.xkcd.com/comics/a_b_2x.png 2x"/> 
</div>
...
```
and compare both: 

> <img src="https://imgs.xkcd.com/comics/a_b.png"> <img src="https://imgs.xkcd.com/comics/a_b_2x.png">

This seem to be available in almost all comic since #1084, but as it's not in (#1079) and (#1551), I guess we should always check.

><hr>

[This](https://github.com/kristianbenoit/XKCD) is what I did before seeing this project.

I did check if we can use this api with press@xkcd.com before posting and here's their answer:

> Of course it's alright. Though it's not like an "official" thing - just how the system works. It's an internal implementation detail we're happy for you to use.
> 
> -davean

**Comment by jonchampagne** [comment]
I've created a pull request implementing support for this. #16

**Comment by TC01** [comment]
Thanks for the idea and patch! I've just merged this into master now. Sorry for my slowness in responding here.
